#ifndef TRANSACTION_H
#define TRANSACTION_H

#include <string>

class Transaction {
public:
    std::string sender;
    std::string receiver;
    double amount;
    std::string signature; // Generated by signing the transaction

    Transaction(std::string from, std::string to, double amt, std::string sign);

    bool verifyTransaction();
};

#endif // TRANSACTION_H